---
title: "Picture Video Bayesian Models"
format: html
---

## Generic Bayes Theorem

$$
p(\theta \vert Y) \propto p(Y \vert \theta)p(\theta)
$$

## Simple Bayesian model

Where ( $i$ ) indexes all observations and ( $j$ ) indexes all  participants.

$Amplitude$ is a vector of observed cortical amplitudes (ssVEP).
$Participant$ is a vector of a participant indices (1 to 19) for each $Amplitude$.

### Linear Model (Likelihood)  {style="text-align: center;"}

$$
\begin{gather}
Amplitude{[i]} \sim Normal(\mu{[i]},\sigma) \tag{1}\\
\mu{[i]} = \alpha{[Participant[i]]} \tag{2}
\end{gather}
$$

### Uninformative Weak Priors {style="text-align: center;"}

$$
\begin{gather}
\alpha[j] \sim Normal(0,2) \tag{3}\\
\sigma \sim HalfNormal(0,2) \tag{4}
\end{gather}
$$

## Simple Multilevel Bayesian model

Where ( $i$ ) indexes all observations and ( $j$ ) indexes all  participants.

$Amplitude$ is a vector of observed cortical amplitudes (ssVEP).
$Participant$ is a vector of a participant indices (1 to 19) for each $Amplitude$.

### Linear Model (Likelihood)  {style="text-align: center;"}

$$
\begin{gather}
Amplitude{[i]} \sim Normal(\mu{[i]},\sigma) \tag{1}\\
\mu{[i]} = \alpha{[Participant[i]]} \tag{2}
\end{gather}
$$

### Multilevel Priors {style="text-align: center;"}

$$
\begin{gather}
\alpha[j] \sim Normal(\overline{\alpha}, \sigma Participant) \tag{3}
\end{gather}
$$

### Uninformative Weak Priors {style="text-align: center;"}

$$
\begin{gather}
\overline{\alpha} \sim Normal(0,2) \tag{4}\\
\sigma \sim HalfNormal(0,2) \tag{5}
\end{gather}
$$

## How missing amplitude are treated

$$
\begin{gather}
Amplitude[1 : all \ possible \ trials]\\
Amplitude[indicesObserved]=AmplitudeObserved\\
Amplitude[indicesMissing]=AmplitudeMissing
\end{gather}
$$

## Model 1 / 2 ML Fatigue, Cues per Phase

Where ( $i$ ) indexes all observations and ( $j$ ) indexes all  participants.

$Amplitude$ is a vector of observed cortical amplitudes (ssVEP).
$Participant$ is a vector of a participant indices (1 to 19) for each $Amplitude$.

### Linear Model (Likelihood)  {style="text-align: center;"}

$$
\begin{gather}
Amplitude{[i]} \sim Normal(\mu{[i]},\sigma[Par[i]]) \tag{1}\\
\mu{[i]} = \alpha{[Par[i]]} +(\beta1[Par[i]] \cdot Trial[i]) + \beta2[Cue[i],Phase[i]] \tag{2}
\end{gather}
$$


### Multilevel Priors {style="text-align: center;"}


$$
\begin{gather}
\alpha[j] \sim TDis(DF = 19, \overline{\alpha}, \sigma _\alpha) \tag{3} \\
\beta1[j] \sim TDis(DF = 19, \overline{\beta1}, \sigma _{\beta1}) \tag{4} \\
\beta2[q, ph] \sim TDis(DF = 12, 0, \sigma _{\beta2}) \tag{5} \\
\sigma[j] \sim HalfTDis(DF = 19, \overline{\sigma}, \tau) \tag{6}
\end{gather}
$$

## Model 3 Rescola Wagner controlling for Fatigue

Where ( $i$ ) indexes all observations and ( $j$ ) indexes all  participants.

$Amplitude$ is a vector of observed cortical amplitudes (ssVEP).
$Participant$ is a vector of a participant indices (1 to 19) for each $Amplitude$.

### Linear Model (Likelihood)  {style="text-align: center;"}

$$
\begin{gather}
Amplitude{[i]} \sim Normal(\mu{[i]},\sigma[Par[i]]) \tag{1}\\
\mu{[i]} = \alpha{[Par[i]]} +(\beta1[Par[i]] \cdot Trial[i]) + (\beta2[Cue[i] \cdot CSPStrength) \tag{2} \\
\\
\text{if Habituation phase:}  \tag{3} \\
CSPStrength[i] = 0 \tag{4} \\
\Delta CSPStrength[i] = 0 \tag{5} \\
CSPStrength[i + 1] = 0 \tag{6} \\
\\
\text{else if Cue is CS+:}  \tag{7} \\
\Delta CSPStrength[i] = LearningRate[Par[i]] \cdot (Paired[i] - CSPStrength) \tag{8} \\
CSPStrength[i + 1] =  CSPStrength[i] + \Delta CSPStrength[i] \tag{9} \\
\\
\text{else:}  \tag{10} \\
\Delta CSPStrength[i] = 0 \tag{11} \\
CSPStrength[i + 1] =  CSPStrength[i] \tag{12} \\
\end{gather}
$$


### Multilevel Priors {style="text-align: center;"}






## Model 1:<br>Multilevel Participant and Stimuli Predictors {style="text-align: center;"}

Where ( $i$ ) indexes all observations, ( $j$ ) indexes all 45 participants, and ( $k$ ) indexes all 90 stimuli.

$Amplitude$ is a vector of observed cortical amplitudes (either LPP or ssVEP).  
$Par$ is a vector of a participant indices (1 to 45) for each $Amplitude$.  
$Stim$ is a vector of stimuli indices (1 to 90) for each $Amplitude$.  

### Linear Model (Likelihood) {style="text-align: center;"}

$$
\begin{gather}
Amplitude_{[i]} \sim Normal(\mu_{[i]},\sigma_{[Par[i]]}) \tag{1}\\
\mu_{[i]} = \beta_{1[Par[i]]} + \beta_{2[Stim[i]]} \tag{2}
\end{gather}
$$

### Adaptive Regularizing Priors {style="text-align: center;"}

$$
\begin{gather}
\beta_{1[j]} \sim Normal(\overline{Par}, \sigma Par) \tag{3}\\
\beta_{2[k]} \sim Normal(0, \sigma Stim) \tag{4}\\
\sigma_{[j]} \sim Normal(\overline{\sigma}, \tau) \tag{5}
\end{gather}
$$

### Uninformative Weak Priors {style="text-align: center;"}

$$
\begin{gather}
\overline{Par} \sim Normal(\overline{Amplitude},2 \cdot SD(Amplitude)) \tag{6}\\
\sigma Par,\sigma Stim,\overline{\sigma},\tau \sim HalfNormal(0,2 \cdot SD(Amplitude)) \tag{7}
\end{gather}
$$

## SNR formula

$$
{\text{Model 1 SNR}} = \frac {\overline{\beta_2 [\text{emotional stimuli}]} - \overline{\beta_2 [\text{neutral stimuli}]}} {\overline{\sigma}} \tag{8}
$$

## Model 2:<br>Multilevel Amplitude and Arousal Bivariate Distribution {style="text-align: center; white-space: nowrap;"}

Where ( $i$ ) indexes all observations and ( $j$ ) indexes all 45 participants. 

$Amplitude$ is a vector of observed cortical amplitudes (either LPP or ssVEP).  
$Arousal$ is a vector of observed arousal ratings aligned with $Amplitude$.  
$Par$ is a vector of a participant indices (1 to 45) for each $Amplitude$.

### Bivariate Distribution (Likelihood) {style="text-align: center;"}

$$
\begin{gather}
\begin{bmatrix}
  Amplitude_{[i]} \\
  Arousal_{[i]}
\end{bmatrix} \sim MVNormal \left(
\begin{bmatrix}
  \mu Amp_{[Par[i]]} \\
  \mu Aro_{[Par[i]]}
\end{bmatrix},
\begin{array}{c}
{\huge \Sigma}_{[Par[i]]}
\end{array}
\right) \tag{9}\\
\begin{array}{c}
{\huge \Sigma}_{[Par[i]]}
\end{array} = 
\begin{bmatrix}
\sigma Amp_{[Par[i]]}^2 & \sigma Amp Aro_{[Par[i]]} \\
\sigma Amp Aro_{[Par[i]]} & \sigma Aro_{[Par[i]]}^2
\end{bmatrix} \tag{10}
\end{gather}
$$





### Adaptive Regularizing Priors {style="text-align: center;"}

$$
\begin{gather}
\mu Amp_{[j]} \sim Normal(\overline{\mu Amp},\sigma Par Amp) \tag{11}\\
\mu Aro_{[j]} \sim Normal(\overline{\mu Aro},\sigma Par Aro) \tag{12}\\
\sigma Amp_{[j]} \sim Normal(\overline{\sigma Amp}, \tau ParAmp) \tag{13}\\
\sigma Aro_{[j]} \sim Normal(\overline{\sigma Aro}, \tau ParAro) \tag{14}\\
\sigma Amp Aro_{[j]} \sim Normal(\overline{\sigma Amp Aro}, \tau AmpAro) \tag{15}
\end{gather}
$$

### Uninformative Weak Priors {style="text-align: center;"}

$$
\begin{gather}
\overline{\mu Amp} \sim Normal(\overline{Amplitude},2 \cdot SD(Amplitude)) \tag{16}\\
\sigma Par Amp,\overline{\sigma Amp},\tau ParAmp,\tau AmpAro \sim HalfNormal(0,2 \cdot SD(Amplitude)) \tag{17}\\
\overline{\mu Aro} \sim (Beta(1.1,1.1) \cdot 8) + 1 \tag{18}\\
\sigma Par Aro,\overline{\sigma Aro},\tau ParAro \sim HalfNormal(0,4) \tag{19}\\
\overline{\sigma Amp Aro} \sim Normal(0,2 \cdot SD(Amplitude)) \tag{20}
\end{gather}
$$



## Model 2 Amplitude log-likelihood equation{style="text-align: center;"}

$$
\begin{gather}
\mu Amp \vert Arousal_{[i]} = \mu Amp_{[Par[i]]} + \frac {\sigma Amp Aro_{[Par[i]]}} {\sigma Aro_{[Par[i]]}^2} (Arousal_{[i]} - \mu Aro_{[Par[i]]}) \tag{21}\\
\sigma Amp \vert Arousal_{[i]}^2 = \sigma Amp_{[Par[i]]}^2 - \frac {\sigma Amp Aro_{[Par[i]]}} {\sigma Aro_{[Par[i]]}^2} \tag{22}
\end{gather}
$$

## R^2 formula

$$
R^2 = \frac {\text{variance of predicted observations}} {(\text{variance of predicted observations } + \text{residual variance})} \tag{23}
$$




## Model 2: Multilevel Participant and Arousal Predictors {style="text-align: center;"}

$$
\begin{gather}
Where \ ( i ) \ indexes \ all \ observations \ and \ ( j ) \ indexes \ 46 \ participants. \\
Where \ ( Amplitude ) \ is \ a \ vector \ of \ observed \ cortical \ amplitudes. \\
Where \ ( Par ) \ is \ a \ vector \ of \ participant \ indices \ for \ each \ amplitude. \\
\end{gather} \\
$$

### Linear Model (Likelihood) {style="text-align: center;"}

$$
\begin{gather}
Amplitude_{[i]} \sim Normal(\mu_{[i]},\sigma) \tag{1}\\
\mu_{[i]} = \beta1_{[Par[i]]} + \beta2_{[Par[i]]} \cdot Arousal_{[i]} \tag{2}
\end{gather}
$$

### Adaptive Regularizing Priors {style="text-align: center;"}

$$
\begin{gather}
\beta1_{[j]} \sim Normal(\bar{Par}, \sigma Par)  \tag{3}\\
\beta2_{[j]} \sim Normal(\bar{\beta2}, \sigma Aro)  \tag{4}
\end{gather}
$$

### Uninformative Weak Priors {style="text-align: center;"}

$$
\begin{gather}
\bar{Par} \sim Normal(\bar{Arousal},2 \cdot SD(Amplitude)) \tag{5}\\
\bar{\beta2} \sim Normal(0, 2 \cdot SD(Amplitude)) \tag{6}\\
\sigma,\sigma Par,\sigma Aro \sim HalfNormal(0,2 \cdot SD(Amplitude)) \tag{7}
\end{gather}
$$



## Model 4: Multilevel participant and stimuli predictors {style="text-align: center;"}

$$
\begin{gather}
Where \ ( i ) \ indexes \ all \ observations, ( j ) \ indexes \ participants,\\ 
and \ ( k ) \ indexes \ stimuli.
\end{gather}
$$

### Linear model {style="text-align: center;"}

$$
\begin{gather}
Amplitude_{[i]} \sim Normal(\mu_{[i]},\sigma) \tag{1}\\
\mu_{[i]} = \beta_{par[i]} + \beta_{stim[i]} \tag{2}
\end{gather}
$$

### Adaptive regularizing priors {style="text-align: center;"}

$$
\begin{gather}
\beta_{par[j]} \sim Normal(\hat{\bar{par}}, \sigma_{par}) \tag{3}\\
\beta_{stim[k]} \sim Normal(0, \sigma_{stim}) \tag{4}
\end{gather}
$$

### Uninformative weak priors {style="text-align: center;"}

$$
\begin{gather}
\hat{\bar{par}} \sim Normal(\bar{par},2 * SD(Amplitude)) \tag{5}\\
\sigma,\sigma_{par},\sigma_{stim} \sim HalfNormal(0,2 * SD(Amplitude)) \tag{6}
\end{gather}
$$
